language: python

python:
  - "3.6.5"

install:
  - pip install -r requirements.txt

script:
  - py.test --cov=app tests/ && coverage report

services:
  - postgres

before_script:
  - psql -c 'create database rides_test;' -U postgres
  - psql -c 'create user rider with password 'pass123';' -U postgres

after_success:
  - coveralls
